[debug] [2021-08-30T01:51:03.946Z] ----------------------------------------------------------------------
[debug] [2021-08-30T01:51:03.948Z] Command:       /usr/local/Cellar/node/15.0.1/bin/node /usr/local/bin/firebase deploy --only hosting
[debug] [2021-08-30T01:51:03.948Z] CLI Version:   7.13.1
[debug] [2021-08-30T01:51:03.949Z] Platform:      darwin
[debug] [2021-08-30T01:51:03.949Z] Node Version:  v15.0.1
[debug] [2021-08-30T01:51:03.950Z] Time:          Sun Aug 29 2021 18:51:03 GMT-0700 (Pacific Daylight Time)
[debug] [2021-08-30T01:51:03.950Z] ----------------------------------------------------------------------
[debug] [2021-08-30T01:51:03.950Z] 
[debug] [2021-08-30T01:51:03.959Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2021-08-30T01:51:03.959Z] > authorizing via signed-in user
[debug] [2021-08-30T01:51:03.959Z] [iam] checking project a-place-to-go-d3310 for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2021-08-30T01:51:03.961Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2021-08-30T01:51:03.961Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2021-08-30T01:51:04.109Z] <<< HTTP RESPONSE 400
[debug] [2021-08-30T01:51:04.111Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/a-place-to-go-d3310:testIamPermissions  

[debug] [2021-08-30T01:51:04.209Z] <<< HTTP RESPONSE 401
[debug] [2021-08-30T01:51:04.209Z] <<< HTTP RESPONSE BODY
[debug] [2021-08-30T01:51:04.210Z] [iam] error while checking permissions, command may fail: FirebaseError: HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[debug] [2021-08-30T01:51:04.211Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2021-08-30T01:51:04.212Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2021-08-30T01:51:04.270Z] <<< HTTP RESPONSE 400
[debug] [2021-08-30T01:51:04.270Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/a-place-to-go-d3310  
 
[debug] [2021-08-30T01:51:04.326Z] <<< HTTP RESPONSE 401
[debug] [2021-08-30T01:51:04.326Z] <<< HTTP RESPONSE BODY
[debug] [2021-08-30T01:51:04.327Z] HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[debug] [2021-08-30T01:51:04.381Z] FirebaseError: HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
    at module.exports (/usr/local/lib/node_modules/firebase-tools/lib/responseToError.js:38:12)
    at Request._callback (/usr/local/lib/node_modules/firebase-tools/lib/api.js:39:35)
    at Request.self.callback (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at Request.emit (node:events:327:20)
    at Request.EventEmitter.emit (node:domain:486:12)
    at Request.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:327:20)
    at Request.EventEmitter.emit (node:domain:486:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:433:28)
    at IncomingMessage.emit (node:events:339:22)
    at IncomingMessage.EventEmitter.emit (node:domain:486:12)
    at endReadableNT (node:internal/streams/readable:1289:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)
[error] 
[error] Error: Failed to get Firebase project a-place-to-go-d3310. Please make sure the project exists and your account has permission to access it.
[debug] [2021-08-30T01:51:39.405Z] ----------------------------------------------------------------------
[debug] [2021-08-30T01:51:39.407Z] Command:       /usr/local/Cellar/node/15.0.1/bin/node /usr/local/bin/firebase deploy
[debug] [2021-08-30T01:51:39.407Z] CLI Version:   7.13.1
[debug] [2021-08-30T01:51:39.407Z] Platform:      darwin
[debug] [2021-08-30T01:51:39.407Z] Node Version:  v15.0.1
[debug] [2021-08-30T01:51:39.408Z] Time:          Sun Aug 29 2021 18:51:39 GMT-0700 (Pacific Daylight Time)
[debug] [2021-08-30T01:51:39.409Z] ----------------------------------------------------------------------
[debug] [2021-08-30T01:51:39.409Z] 
[debug] [2021-08-30T01:51:39.417Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2021-08-30T01:51:39.418Z] > authorizing via signed-in user
[debug] [2021-08-30T01:51:39.418Z] [iam] checking project a-place-to-go-d3310 for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2021-08-30T01:51:39.419Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2021-08-30T01:51:39.420Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2021-08-30T01:51:39.521Z] <<< HTTP RESPONSE 400
[debug] [2021-08-30T01:51:39.523Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/a-place-to-go-d3310:testIamPermissions  

[debug] [2021-08-30T01:51:39.575Z] <<< HTTP RESPONSE 401
[debug] [2021-08-30T01:51:39.576Z] <<< HTTP RESPONSE BODY
[debug] [2021-08-30T01:51:39.577Z] [iam] error while checking permissions, command may fail: FirebaseError: HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[debug] [2021-08-30T01:51:39.578Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2021-08-30T01:51:39.579Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2021-08-30T01:51:39.645Z] <<< HTTP RESPONSE 400
[debug] [2021-08-30T01:51:39.645Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/a-place-to-go-d3310  
 
[debug] [2021-08-30T01:51:39.701Z] <<< HTTP RESPONSE 401
[debug] [2021-08-30T01:51:39.701Z] <<< HTTP RESPONSE BODY
[debug] [2021-08-30T01:51:39.701Z] HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
[debug] [2021-08-30T01:51:39.761Z] FirebaseError: HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
    at module.exports (/usr/local/lib/node_modules/firebase-tools/lib/responseToError.js:38:12)
    at Request._callback (/usr/local/lib/node_modules/firebase-tools/lib/api.js:39:35)
    at Request.self.callback (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at Request.emit (node:events:327:20)
    at Request.EventEmitter.emit (node:domain:486:12)
    at Request.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:327:20)
    at Request.EventEmitter.emit (node:domain:486:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/firebase-tools/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:433:28)
    at IncomingMessage.emit (node:events:339:22)
    at IncomingMessage.EventEmitter.emit (node:domain:486:12)
    at endReadableNT (node:internal/streams/readable:1289:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)
[error] 
[error] Error: Failed to get Firebase project a-place-to-go-d3310. Please make sure the project exists and your account has permission to access it.
